### ISSUE TITLE
AESPrivacyProvider from .NETCoreApp version 2.2

### ISSUE THREAD

**Issue by mjsiers** [lextm/sharpsnmplib#100]
I am currently using version 10.0.11 of the library with a .NETCoreApp (version 2.2).
Everything is working great but I would also like to be able to support using both 
DES and AES encryption for sending V3 trap messages but I believe the function Security.AESPrivacyProviderBase.IsSupported returns False.

Is there any way for me to enable AES support within a .NETCoreApp at version 2.2?

**Comment by lextm** [comment]
Already documented in https://docs.sharpsnmp.com/tutorials/aes.html#providers-on-bouncy-castle

Duplicate to #81
