### ISSUE TITLE
SNMP V3 Unhandled Exception: System.InvalidCastException: Value should be from 0 to 7

### ISSUE THREAD

**Issue by sweetpants** [lextm/sharpsnmplib#101]
When using SNMP V3 discovery on a Cisco ASA 5510 firewall, this device returns MsgFlags = 8, but the library only handles 0-7. When using a Cisco C2960 switch, which returns MsgFlags = 0, everything is working fine. Attached a pcap of the two devices (10.252.0.1 = ASA, 192.168.128.13 = Switch)
[asa_vs_switch_discovery.pcap.zip](https://github.com/lextm/sharpsnmplib/files/2764120/asa_vs_switch_discovery.pcap.zip)

BTW, Net::SNMP works fine on the same ASA device

**Comment by sweetpants** [comment]
The error is generated from OctetString.cs line 163. Is it possible to do a logical AND with 0x7 ? RFC3412 is clear that only the 3 lowest bits are used. Getting Cisco to change this in their code will be a lengthy process i presume.

**Comment by lextm** [comment]
Closed via #102
