### ISSUE TITLE
Agent atomic set/get operations

### ISSUE THREAD

**Issue by astrowalker** [lextm/sharpsnmplib#105]
At the client side I can see that I can pass several variables to set or get for Messenger so I assume those operations are atomic.

But on the agent side I have nodes with `Data` properties. Let's say I have two nodes `X` and `Y` and their values are `0`. I would like to set them atomically to `1, 1` -- this means that client reading those nodes should never get the readout `0, 1` or `1, 0`.

And in reverse, when client sets in single operation those nodes to `2, 2` (for example) agent should get those values "together", so it won't read something like `1, 2` or `2, 1`.

So, how to make agent to work atomically on given nodes?

*Would approach with single lock on both nodes (for C# getter and setter) be a sane solution in terms of SNMP/SharpSnmpLib principles)? With single lock one couldn't execute C# getter until all C# setters are finished.*

**Comment by lextm** [comment]
https://docs.sharpsnmp.com/samples/agent-development.html#limitation-explained

**Comment by astrowalker** [comment]
Thank you, but I don't see anything related to atomicity in this section, neither in `MainForm.cs`.

**Comment by lextm** [comment]
"This sample is provided to demonstrate how the library might be used. If you want to build a full feature SNMP agent based on this sample, then many changes (mult-threading and security related) are mandate."
