### ISSUE TITLE
Snmp V3 Walk Example is obsolete

### ISSUE THREAD

**Issue by develorem** [lextm/sharpsnmplib#107]
The documentation on the site indicates to use the Messenger.BulkWalk method to do a walk in Snmp V3.
However the method is marked as Obsolete and I cannot find a practical example for using the other overload.

The documentation should be updated to reflect the correct implementation to perform a walk with SNMP v3. 

Note: The BulkWalkAsync version with the same parameters is also marked obsolete.

**Comment by lextm** [comment]
If you check the source code, only one of the overloading methods is marked as obsolete,

https://github.com/lextm/sharpsnmplib/blob/master/SharpSnmpLib/Messaging/Messenger.cs
