### ISSUE TITLE
SnmpMessageExtension.GetReponseAsync throws ArgumentException when response is malformed with report PDU and version 2.

### ISSUE THREAD

**Issue by lawrencejohnston** [lextm/sharpsnmplib#11]
We're calling SnmpMessageExtension.GetReponseAsync on an ISnmpMessage with the version set to 2 and it's failing with this exception:

> System.AggregateException: One or more errors occurred. ---> System.ArgumentException: only v3 is supported
> Parameter name: version
>    at Lextm.SharpSnmpLib.Messaging.ReportMessage..ctor(VersionCode version, Header header, SecurityParameters parameters, Scope scope, IPrivacyProvider privacy, Byte[] length)
>    at Lextm.SharpSnmpLib.Messaging.MessageFactory.ParseMessage(Int32 first, Stream stream, UserRegistry registry)
>    at Lextm.SharpSnmpLib.Messaging.MessageFactory.ParseMessages(Byte[] buffer, Int32 index, Int32 length, UserRegistry registry)
>    at Lextm.SharpSnmpLib.Messaging.SnmpMessageExtension.<GetResponseAsync>d__14.MoveNext()

I suspect the cause is that the server we're communicating with (which we don't control) is returning a malformed response with the report pdu type but the version is set to 2.

It seems like in this case an SnmpException should be thrown instead of an ArgumentException when this happens since the problem is caused by the response from the remote server and not any a malformed argument provided by our code.

**Comment by lextm** [comment]
Thanks for the report. I think MessageFactory should wrap up the `ArgumentException` to a more suitable exception type.

This will be fixed in the upcoming 9.5 release.

**Comment by lawrencejohnston** [comment]
That makes sense to me. Thanks!
