### ISSUE TITLE
Make ObjectStore implement IObjectStore

### ISSUE THREAD

**Issue by schweinsbauch** [lextm/sharpsnmplib#12]
see Issue on codeplex nr Id #7286
https://sharpsnmplib.codeplex.com/workitem/7286

Make ObjectStore inherit from an Interface: IObjectStore, in order to allow customization of the ObjectStore: 
https://sharpsnmplib.codeplex.com/SourceControl/latest#SharpSnmpLib/Pipeline/ObjectStore.cs 

This is necessary for applications which do not necessarly know all OID's managed by the SNMP Server. The Current Implementation requires knowledge of all OID's on startup/before requesting the Object. 

public interface IObjectStore{ 
public ScalarObject GetObject(ObjectIdentifier id); 
public ScalarObject GetNextObject(ObjectIdentifier id); 
public void Add(ISnmpObject newObject); 
}

**Comment by lextm** [comment]
Fixed in #14.
