### ISSUE TITLE
Error NoSuchName {"error in response"}

### ISSUE THREAD

**Issue by josephkandi** [lextm/sharpsnmplib#17]
I trying the library and am using the sample code. I can use snmpwalk and it works fine :
 `snmpwalk -v 1 -c public localhost .1.3.6.1.2.1.1.4`

**Output :**
`SNMPv2-MIB::sysContact.0 = STRING: Administrator admin@test.com
End of MIB`

I also used  **ManageEngine MIBBrowser** and it works fine, but using the library i keep getting the error **{"error in response"}** and when i check the detail of the error, the **ErrorStatus** is **NoSuchName**.

Here is my code 
```c#
var result = Messenger.Get(VersionCode.V1,
                           new IPEndPoint(IPAddress.Parse("192.168.0.101"), 161),
                           new OctetString("public"),
                           new List<Variable> { new Variable(new ObjectIdentifier(ObjectIdentifier.Convert(".1.3.6.1.2.1.1.4"))) },
                           60000);
```

What am i doing wrong?

**Comment by josephkandi** [comment]
I managed to get past the Exception. The issue was the wrong VersionCode. Now i get the NoSuchObject as a result.

**Comment by lextm** [comment]
Please post such questions to StackOverflow.com or ServerFault.com. It has nothing to do with this library, and has been answered so many times. In your case, study what is a scalar object and why .0 must be appended to the end of its OID to query the value.
