### ISSUE TITLE
Problem with v3-Walk

### ISSUE THREAD

**Issue by Lesnik4u** [lextm/sharpsnmplib#22]
![2016-09-26 23-54-48 nagios xi - configuration - mozilla firefox](https://cloud.githubusercontent.com/assets/17494479/19355251/6508e1d8-9172-11e6-823b-703ddf24ddbc.png)
![2016-09-26 23-45-22 nagios xi - configuration - mozilla firefox 2](https://cloud.githubusercontent.com/assets/17494479/19355250/6503d472-9172-11e6-9471-94efcae6bdf3.png)

I've created an SNMP Agent based on the **#SNMP Library** v9.0.2.
I've found strange behavior concerning **v3 Walk**.
Please see the screenshots.
I’ve tested this with **Nagios XI**.
**Get** requests are processed correctly for any version of protocol (v1-v3).
Single **GetNext** is also processed **correctly**.
**Walk** under v1 and v2c are also processed **correctly**.
But there is a **problem** with **Walk under v3** .
Only the first **GetNext** request is transferred to its handler (GetNextMessageHandler.Handle() ), the next one is ignored by #SNMP library for some reason. Then Nagios tries to request **GetNext** again several times, does not get any further response and then reports a **timeout**. engine.ExceptionRaised is not triggered.
**So v3 Walk fails.**

Paessler SNMP tester can do v3 Walk with #SNMP library. But I see that this tester does this in a different way:
1. It sends two Get Requests after one GetNext request (one to get UpTime, and another - a value of the object)
2. It sends three different GetNext requests per object and only one of these requests is processed by the library.

Probably SNMP Tester has better degree of compatibility? Or probably this tester's way of alternation of **Get** and **GetNext** makes #SNMP library work better?

Also I've tested Nagios v3-Walk against Power SNMP library. It works correctly. So I suspect that something can be wrong in #SNMP library, or probably it lacks some settings from my side?

Has anybody tested v3-Walk with #SNMP library based agent against Nagios XI or some other popular products?
Do you have ideas about how can we fix v3 Walk with it?

**Comment by lextm** [comment]
It is rather strange that WALK in v3 uses GETNEXT instead of GETBULK. Can you capture network packets in v3 noAuthNoPriv mode using Nagios, and share them? That should help me dig further into the issue.

**Comment by martin-danek** [comment]
I've found an issue with SNMPv3 authentication, which could be related to this problem.

In my scenario, SharpSnmpLib is also used in an agent running on our server. The client part is snmpwalk from linux net-snmp package. The client usually reads zero to one, max two, messages and then stops with error message "snmpwalk: Not in time window", which is an error message received from the server.
SNMPv2 works fine as well.

I think this is a bug in SharpSnmpLib. I've tracked it down to a condition in Lextm.SharpSnmpLib.Pipeline.EngineGroup.IsInTime()
------------
var diff = currentTimeData[1] > pastTime ? currentTimeData[1] - pastTime : currentTimeData[1] - pastTime - int.MinValue + int.MaxValue;
return diff >= 0 && diff <= 150;
------------
which evaluates to false when the client message contains the same time as the current time on the server (in other words: works only when 1 second elapsed between previous message and this one).

Is this the same issue or should I open a different one? I could probably send in a pull request for my problem, changing the condition to
var diff = currentTimeData[1] >= pastTime ? currentTimeData[1] - pastTime : pastTime - currentTimeData[1];
though I still can't understand why was the "- int.MinValue + int.MaxValue" part there (this part always evaluates to -1).

Feel free to ask for details on reproducing this behaviour.

**Comment by lextm** [comment]
@martin-danek yours is duplicate to #20 . Please upgrade to 9.0.5 via NuGet and try again.

**Comment by martin-danek** [comment]
Oh, that's it. Sorry for not noticing the fix. Seems to work OK after upgrading. Thank you.

**Comment by Lesnik4u** [comment]
Thank you for your hint about GETNEXT/GETBULK.
That was **my fault** not turning on **support for GetBulk** handlers when using your library. 

_(What confused me - is that some programs were still able to walk via v3 though GetBulk was turned off. 
The reason why other programs was able to do this is that they also do not support GetBulk or they were adaptively using GetNext in the case if GetBulk not responded.)_

So, **turning on GetBulk** support **solved the problem**.

**Comment by lextm** [comment]
SNMP message handlers must match the behaviors defined by different RFC documents. Thus, to make an agent you need to register handlers in the proper way.

The sample project shows the recommended approach, which you can see from this file,

https://github.com/lextm/sharpsnmplib/blob/master/snmpd/MainForm.cs#L34
