### ISSUE TITLE
ObjectStore is not easily extendable

### ISSUE THREAD

**Issue by Quintinon** [lextm/sharpsnmplib#28]
The **Lextm.SharpSnmpLib.Pipeline.ObjectStore** class is difficult to extend because of two problems:

- The **_list** field is marked as private.
- The **Add** method is not marked as virtual.

This results in either:
- A derived class needing to use the **ObjectStore** implementation of **Add** without being able to change the functionality.
- A derived class hiding the **ObjectStore** implementation of **Add** with the keyword _new_ and then hoping no calls to **ObjectStore**.**Add** are made.

I see that an IObjectStore was proposed in #12 / #13 but would cause a lot of code change and instead #14 was implemented which made extending the ObjectStore possible, but not completely feasible.

I propose the following:

- Changing **_list** to be protected.
- Changing **Add** to be virtual.

**Comment by lextm** [comment]
Closed via #29
