### ISSUE TITLE
Error signing output with public key

### ISSUE THREAD

**Issue by clefranc** [lextm/sharpsnmplib#31]
Hi,
I've been using your tool for quite some years, compiling the source code on my computer. Each time I must remove the signature file. I understand a commercial product need some kind of tampering protection, but does a public repository on Github needs this?
```
Error	CS7027	Error signing output with public key from file 'sharpsnmplib.snk' -- File not found.	SharpSnmpLib.NetStandard	E:\Visual Studio 2017\sharpsnmplib-9.0.8\SharpSnmpLib\CSC	1	Active
```

**Comment by lextm** [comment]
You need to run prepare.bat or prepare.sh before compilation. I don't want to share the private key yet. Note that signing an assembly is not "tampering protection" at all. Study some basics on assembly signing and you see why.

**Comment by gabrielpereirapinheiro** [comment]
Where I found the file "prepare.bat" ?

**Comment by lextm** [comment]
@gabrielpereirapinheiro https://docs.sharpsnmp.com/getting-started/installing-on-windows.html#install-snmp-library-via-source-code

**Comment by lextm** [comment]
@gabrielpereirapinheiro Read it carefully, as prepare.bat is no longer needed since a recent version.

**Comment by gabrielpereirapinheiro** [comment]
@lextm That true, thanks for the help !
