### ISSUE TITLE
Throw an exception if SNMP-GetNext-Response returns the same OID as the SNMP-GetNext-Request

### ISSUE THREAD

**Issue by jrost** [lextm/sharpsnmplib#33]
I know the behavior of devices which send the same OID in the GetNextEntry - response at which getNext was querried are **not** standard conform. But this leeds to an endless loop with the walk command. 

It would be nice if it would just throw an exception which stops this endless loop.

With best regards.

**Comment by lextm** [comment]
No plan to support all non-standard-compliant cases.
