### ISSUE TITLE
What do I do with a Variable?

### ISSUE THREAD

**Issue by xxbiohazrdxx** [lextm/sharpsnmplib#34]
There is virtually no documentation on the Variable class and what can be done with it. The only real example I see is in the SnmpGet sample

`foreach (Variable variable in Messenger.Get(version, receiver, new OctetString(community), vList, timeout))
{
     Console.WriteLine(variable);
}`

That's great if I want to write it to the console, but if I want to do a comparison on the returned value I have no way of getting it to an bool/int/string or whatever type corresponds to the returned value;

There are no conversion methods as far as I can tell, I can't use it in any constructors for data types. How do I actually get useful information out the Variable?

**Comment by lextm** [comment]
For #SNMP Library users, you can first grab the data from `Variable.Data` and then use `ISnmpData` interface to check `TypeCode`,

https://help.sharpsnmp.com/html/T_Lextm_SharpSnmpLib_ISnmpData.htm

and then cast the data to corresponding `ISnmpData` derived classes, such as `Counter32`.
