### ISSUE TITLE
Modifying Users

### ISSUE THREAD

**Issue by BWillis98** [lextm/sharpsnmplib#35]
There's no way to modify the usm table. Why not?

**Comment by lextm** [comment]
Please go and challenge the original authors of the standard. That goes beyond the scope of any SNMP library.

**Comment by BWillis98** [comment]
You have a method to add users, but I figured out another way. My problem was doing a discovery via IP address, like SnmpSharpNet does.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by lextm** [comment]
Please start from the documentation site,

https://docs.sharpsnmp.com/en/latest/
