### ISSUE TITLE
Why can't I instanciate: new ObjectIdentifier("1")

### ISSUE THREAD

**Issue by KarloX2** [lextm/sharpsnmplib#36]
Hi!

When I do this 
`new ObjectIdentifier("1")`

(i.e. parsing the OID value string "1" which is what the "iso" node of the SNMPv2-SMI MIB refers to), I get an ArgumentException saying "The length of the shortest identifier is two".

Why? I think the OID "1" (and also "0") should be perfectly legal.

Thanks
Karlo

**Comment by lextm** [comment]
However, single digit OIDs are illegal,

https://blog.lextudio.com/snmp-pro-secrets-behind-object-identifier-ff242fd4474e
