### ISSUE TITLE
Why are OIDs printed with a starting dot

### ISSUE THREAD

**Issue by KarloX2** [lextm/sharpsnmplib#37]
Hello,

Can you please tell me why the ObjectIdentifier.ToString() method will return all OIDs with a starting dot?

Thanks

**Comment by lextm** [comment]
Thanks for reporting this.It seems that the starting dot should be removed now to match RFC 3061. Will ship a new release to address that.

**Comment by lextm** [comment]
Fixed in 9.2.0 release.
