### ISSUE TITLE
Wrong value in <Version> tag

### ISSUE THREAD

**Issue by clefranc** [lextm/sharpsnmplib#40]
In the SharpSnmpLib.NetStandard.csproj file, a typo in the `<Version>` tag prevents compilation.
```
<Version>9.2.0-
</Version>
```

**Comment by lextm** [comment]
Fixed in b0c6c8fe5a89ce4baa953d03e235e086f9d51ed7 already.

**Comment by clefranc** [comment]
Please check the [9.2.0](https://github.com/lextm/sharpsnmplib/releases/tag/9.2.0) release source code (zip).

**Comment by lextm** [comment]
Just moved the tag. It should work now.
