### ISSUE TITLE
ReportMessage has no constructor for creating a new PDU

### ISSUE THREAD

**Issue by KarloX2** [lextm/sharpsnmplib#41]
Hello,
the ReportMessage class (unlike other ..Message classes) seems to have no constructor capable for creating a new PDU. To the only existing constructor one must provide the PDU (scope), which makes sense when deserializing incoming data.

Is that intended? 

Thanks

**Comment by KarloX2** [comment]
I just learned that creating report message is being handled in SecureSnmpContext.

**Comment by lextm** [comment]
The nature of `ReportMessage` makes it less likely an option to be constructed compared to other message types. Like you found out, within #SNMP Library, only the agent (pipeline) has a need to construct it as responses to certain SNMP v3 inquiries.
