### ISSUE TITLE
DiscoverAsync returns 0.0.0.0 IP address

### ISSUE THREAD

**Issue by szilardx** [lextm/sharpsnmplib#42]
As described in the title, when I use DiscoverAsync, in the AgentFound event the e.Agent property return 0.0.0.0 instead of the proper ip address.

Discover works fine.
Using latest 9.2 version.
Thanks!

**Comment by lextm** [comment]
Turned out to be a bug.

**Comment by szilardx** [comment]
Thanks for the fix! 👍
