### ISSUE TITLE
nuget Dependencies

### ISSUE THREAD

**Issue by wiredbarb** [lextm/sharpsnmplib#45]
I am trying to use the nuget package Lextm.SharpSnmpLib in a .NET Framework 4.6.1 project. Installing it will add a reference to SharpSnmpLib.NetStandard with target framework _.NETStandard,Version=v1.3_. Unless respective nuget packages (e. g. System.Net.Sockets) are installed additionally, executing SharpSnmpLib code will throw "Could not load file or assembly" exceptions for dependencies that are already included in .NET Framework.
Is there a way to fix this?

**Comment by lextm** [comment]
The design of .NET Standard 1.x so far poses such limitation.

You have to currently manually add NuGet reference to the following,
```
        <dependency id="NETStandard.Library" version="1.6.1" />
        <dependency id="System.ComponentModel.TypeConverter" version="4.3.0" />
        <dependency id="System.Net.NetworkInformation" version="4.3.0" />
        <dependency id="System.Runtime.Serialization.Primitives" version="4.3.0" />
        <dependency id="System.Threading.Thread" version="4.3.0" />
```
and also add to `app.config` the following redirection,
```
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Net.NetworkInformation" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-4.1.1.0" newVersion="4.1.1.0"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Net.Sockets" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-4.1.1.0" newVersion="4.1.1.0"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime.Serialization.Primitives" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-4.1.2.0" newVersion="4.1.2.0"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Security.Cryptography.Primitives" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-4.0.1.0" newVersion="4.0.1.0"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Threading.Thread" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-4.0.1.0" newVersion="4.0.1.0"/>
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
```
> Note that the version numbers might change in the future due to package update.

.NET Standard 2.0 might introduce some easier solutions. We will see.

**Comment by clefranc** [comment]
I had to manually install these packages via NuGet console to compile plain 9.2.0:

```
Install-Package System.Net.Sockets -Version 4.1.0
Install-Package System.Net.NetworkInformation -Version 4.1.0
Install-Package System.Runtime.Serialization.Primitives -Version 4.1.1.0
Install-Package System.Runtime -Version 4.1.0.0
Install-Package System.Runtime.Extensions -Version 4.1.0.0
Install-Package System.IO -Version 4.1.0.0
```
Then I bumped .NETStandard to 1.5 to match my 4.6.2 framework project.

Having these dependencies put in sharpsnmplib would have save me a lot of time consuming search for a resolution.

**Comment by wiredbarb** [comment]
Thanks for looking into it. Though this would not solve the actual issue (which I understand is a wontfix for now), maybe you could add these to the net46 target framework dependencies in your nuspec for convenience. Afaik, nuget will also automatically update config files with appropriate assembly redirects by default.

**Comment by lextm** [comment]
The next release would include such dependencies, but I don't think NuGet would update `app.config` as smart as it should be.
