### ISSUE TITLE
System.IO.FileNotFoundException: System.Net.Sockets

### ISSUE THREAD

**Issue by Cedware** [lextm/sharpsnmplib#47]
Hello,
I tried to launch a simple Agent application, but I keep receiving a exception, telling that the file or assebmly System.Net.Socker can not be found  at `SnmpEngine.start`

**Comment by lextm** [comment]
https://github.com/lextm/sharpsnmplib/blob/master/snmpd/app.config

Currently you have to set assembly redirection.
