### ISSUE TITLE
Repeated password string incorrectly passes authentication

### ISSUE THREAD

**Issue by jameslow261** [lextm/sharpsnmplib#49]
For both authentication and privacy checks, i.e. MD5/SHA1 and DES/AES, there is an issue with repeated passwords being incorrectly treated as valid.

E.g. if the password for either is 'password123', if I send a SNMPv3 GET with 'password123password123', it still succeeds.

I've tried changing the algorithms between MD5/SHA1, DES/AES, and they all have the same issue.
I've also tried creating long passwords with many special characters and the issue still persists.

**Comment by lextm** [comment]
As the related commit shows, the behavior you described can be reproduced in the hashing phase.

The hash generated can be exactly the same, only if you repeat the password multiple times. A tiny change in the password (`s`->`5`) would break. Thus, I don't think it is a security issue at all (anyway you need to know the exact password).

The cause of this behavior I think is the hashing method itself. Currently found no documentation on that side. Will provide an update if I later find anything.
