### ISSUE TITLE
Dependencies are not correctly declared for .NET 4.7.

### ISSUE THREAD

**Issue by lawrencejohnston** [lextm/sharpsnmplib#50]
I originally filed this issue at https://github.com/dotnet/core/issues/877 but it sounds like it's actually a SharpSnmpLib issue.

**Comment by lextm** [comment]
You might try the latest build,

https://www.nuget.org/packages/Lextm.SharpSnmpLib/10.0.0-beta1

With the new .NET Core 2.0 tooling, the issue should have been fixed.

**Comment by lawrencejohnston** [comment]
The beta does seem to have fixed this issue. Thanks.
