### ISSUE TITLE
Missing PrivacyProviders in version 10.0

### ISSUE THREAD

**Issue by SteveMelan** [lextm/sharpsnmplib#53]
Hello,

Have you changed something to the PrivacyProviders as the AESPrivacyProvider is no longer avaiable? :-(

Best regards,

Steve

**Comment by lextm** [comment]
The documentation has been updated,

https://docs.sharpsnmp.com/en/latest/getting-started/installing-on-windows.html#install-snmp-library-via-nuget

You need to install another NuGet package.
