### ISSUE TITLE
BulkWalkAsync infinite loop

### ISSUE THREAD

**Issue by kmiller77** [lextm/sharpsnmplib#55]
The variable "next" is never being updated inside BulkWalkAsync, so you are always looking at the same List of Variables and the same seed, and therefore always seeing that it "has next". You then get stuck in the while loop. In BulkWalk next is an out parameter so it's being updated, but here it's never getting updated.

**Comment by lextm** [comment]
Please upgrade to 10.0.2 release.

**Comment by kmiller77** [comment]
Perfect thanks so much!
