### ISSUE TITLE
Bulkwalk return different data than simple get

### ISSUE THREAD

**Issue by szilardx** [lextm/sharpsnmplib#58]
If I use Bulkwalk, to get MAC address data from a Samsung ML-3470, I get 00-01-00-00-00 MAC address as answer.
If I use a simple get command to get the exact oid, I get the proper MAC address. 

Thanks for the help with these.

This is the Bulkwalk:
`List<Variable> res = new List<Variable>();
Messenger.BulkWalk(VersionCode.V2, 
                                      e.Agent,
                                       new OctetString(Properties.App.Default.community),
                                       new ObjectIdentifier("1.3.6.1.2.1.2.2.1.6"),
                                       res, 
                                       14000, 
                                       4, 
                                       WalkMode.WithinSubtree, 
                                       null, 
                                       null);`
Returns this 00-01 MAC address on OID 1.3.6.1.2.1.2.2.1.6.1 and 1.3.6.1.2.1.2.2.1.6.6.

This Get command:
`                 IList<Variable> res = Messenger.Get(
                                v,
                                e.Agent,
                                new OctetString(Properties.App.Default.community),
                                new List<Variable> {
                                    new Variable(new ObjectIdentifier("1.3.6.1.2.1.2.2.1.6.1"))
                                },
                                7000);`

This gets the proper MAC address.

Other devices have no issues.

**Comment by lextm** [comment]
https://docs.sharpsnmp.com/en/latest/tutorials/troubleshooting.html

You need to do some initial troubleshooting to collect more information.

**Comment by szilardx** [comment]
Sorry for forgetting that step.
I did the troubleshooting steps, and it seems like a device issue, as net-snmp, and packet inspecting confirmed, that not only sharpsnmp had this issue.

I found googling that the device might have an issue with a too bing bulkget message size.
Reducing the number of **maxrepetitions parameter to 1** in the bulkwalk call I was able to get the proper answer from the device.

Can you explain what does max repetitions mean exactly, if I want to get results from a given subtree? (I was not able to completely understand from my googling.)

Thank you very much for your help! 👍

**Comment by lextm** [comment]
It would be difficult to understand the GET BULK operation without knowing what exactly the SNMP agent does, so you might refer to the following #SNMP Agent code,

https://github.com/lextm/sharpsnmplib/blob/master/SharpSnmpLib/Pipeline/GetBulkMessageHandler.cs#L78
