### ISSUE TITLE
DESPrivacyProvider is not working with .net Core

### ISSUE THREAD

**Issue by swenz** [lextm/sharpsnmplib#61]
Hi,

currently I try to use the DESPrivacyProvider to get some bulk data from a Netgear Switch by I always get the following exception:

> System.PlatformNotSupportedException: Operation is not supported on this platform.
>    at Lextm.SharpSnmpLib.Security.DESPrivacyProvider.Encrypt(Byte[] unencryptedData, Byte[] key, Byte[] privacyParameters)
>    at Lextm.SharpSnmpLib.Security.DESPrivacyProvider.Encrypt(ISnmpData data, SecurityParameters parameters)
>    at Lextm.SharpSnmpLib.Security.PrivacyProviderExtension.ComputeHash(IPrivacyProvider privacy, VersionCode version, Header header, SecurityParameters parameters, ISegment scope)
>    at Lextm.SharpSnmpLib.Messaging.GetBulkRequestMessage..ctor(VersionCode version, Int32 messageId, Int32 requestId, OctetString userName, Int32 nonRepeaters, Int32 maxRepetitions, IList`1 variables, IPrivacyProvider privacy, Int32 maxMessageSize, ISnmpMessage report)
>    at Netgear.Client.NetgearClient.GetStatistics(String host, String username, String password, String encryptionKey) in C:\Users\R2D2\Documents\admin.wenz.io\Netgear.Client\NetgearClient.cs:line 23
>    at admin.wenz.io.Web.Tasks.GetStatistics(PerformContext context) in 

I guess this is by design because of line 103-105: https://github.com/lextm/sharpsnmplib/blob/master/SharpSnmpLib/Security/DESPrivacyProvider.cs

This is my code for connection:

```
            Discovery discovery = Messenger.GetNextDiscovery(SnmpType.GetRequestPdu);
            ReportMessage report = discovery.GetResponse(60000, new IPEndPoint(IPAddress.Parse(host), 161));
            var auth = new SHA1AuthenticationProvider(new OctetString(password));
            var priv = new DESPrivacyProvider(new OctetString(encryptionKey), auth);

            GetBulkRequestMessage request = new GetBulkRequestMessage(VersionCode.V3, Messenger.NextMessageId, Messenger.NextRequestId, new OctetString(username), 0, int.MaxValue, new List<Variable> { new Variable(new ObjectIdentifier("1.3.6.1.2.1.2.2.1.16")) }, priv, Messenger.MaxMessageSize, report);
            ISnmpMessage reply = request.GetResponse(60000, new IPEndPoint(IPAddress.Parse(host), 161));


            var result = reply.Pdu().Variables;
```

Is there some work around to still connect to my switch with ASP.net core 2?

Thanks,
Steffen

**Comment by lextm** [comment]
Thanks. You just remind me of the fact that DES is back on .NET Core 2.0.

I will soon ship a new version to address that.

**Comment by lextm** [comment]
10.0.3 has been uploaded to NuGet.org. You should be able to use it once the sync finishes.

**Comment by swenz** [comment]
Thanks for the fast implementation, your change works for me.

Best regards,
Steffen
