### ISSUE TITLE
OctetString Field (with Hex values) delivers false values!

### ISSUE THREAD

**Issue by SearchForTheCode** [lextm/sharpsnmplib#62]
I am getting a field from an HP server (.1.3.6.1.4.1.232.11.2.10.7.0). This field contains status infos as a octect string (hex values).

Sadly the delivered values does not match and are faulty. 

For example with another MIB Browser (ireasoning) i get the correct values:

0x02 04 02 02 02 02 02 02 02 02 01 01 01 02 04 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

If i use the sharp snmp lib the values are completly different (no matter what way i try to receive them via toHexString or get the byte array and convert it myself.)

It is totally weird as there are other OIDs from HP with the same format and are working. 

I am using 9.1.401.1 of your lib (due to 4.5 restrictions in my project).

Any ideas how i can debug this or provide infos on this issue to help resolve it? Thank you

**Comment by SearchForTheCode** [comment]
Nothing? :)

**Comment by lextm** [comment]
The documentation is clear,

https://docs.sharpsnmp.com/en/latest/tutorials/troubleshooting.html
