### ISSUE TITLE
return Numeric(float)

### ISSUE THREAD

**Issue by dborzouei** [lextm/sharpsnmplib#69]
hi, how can i get back Numberic(float)
in `ScalarObject` 
```
public override ISnmpData Data
        {
            get { return 2.1 }
            set { throw new AccessFailureException(); }
        }
```

**Comment by lextm** [comment]
SNMP does not have a data type for float numbers. You might use alternatives such as returning a string.

**Comment by dborzouei** [comment]
i use Zabbix server monitoring , and in agent i return Temperature with float type value .
i try create graph for this value . but zabbix not allow create graph for text value 
and in zabbix we have (numeric (float)) 
![image](https://user-images.githubusercontent.com/8321129/37459562-c07ce932-285d-11e8-90bd-873dcd5cc706.png)
