### ISSUE TITLE
Date Values are wrong

### ISSUE THREAD

**Issue by jasondicker** [lextm/sharpsnmplib#70]
I'm doing a BulkWalk of the hrSWInstalledTable table (.1.3.6.1.2.1.25.6.3), but the date values for hrSWInstalledDate (.1.3.6.1.2.1.25.6.3.1.5) are being returned incorrectly i.e. C# is reporting a value of "?	-".

I have confirmed that my servers have valid dates (for the above OID) via the MIBBrowser tool (Windows platform) & the snmpwalk utility (Linux platform), for example:

The output from snmpwalk is as follows:
...
.1.3.6.1.2.1.25.6.3.1.5.1 = STRING: 2017-2-16,7:44:59.0,+2:0
...

But the BulkWalk method is returning a value of "?	-" in C#.

I've tried decoding this value, to no avail...

My code is as follows:
            var task = Messenger.BulkWalkAsync(
                             VersionCode.V2,
                             new IPEndPoint(IPAddress.Parse(ip), 161),
                             new OctetString(communityString),
                             null,
                             new ObjectIdentifier("1.3.6.1.2.1.25.6.3"),
                             result,
                             10,
                             WalkMode.WithinSubtree,
                             null,
                             null);

Please assist.

**Comment by lextm** [comment]
It is by design.

DateAndTime support is exclusively part of #SNMP Pro,

https://blog.lextudio.com/snmp-pro-dateandtime-syntax-support-e99abc51bc2f
