### ISSUE TITLE
problem with the query 1.3.6.1.2.1.43.18.1.1.7

### ISSUE THREAD

**Issue by manellopez** [lextm/sharpsnmplib#77]
good I would like to know why when I make this query in c # with the code 1.3.6.1.2.1.43.18.1.1.7 I get an error with other codes such as 1.3.6.1.2.1.1.1.0 goes well
If someone could help me, I would be very grateful

**Comment by lextm** [comment]
This library only helps you send the requests. What would be the responses from the actual SNMP agents you are talking about is out of scope. You need to either check the agent documentation and contact its vendor.
