### ISSUE TITLE
Unable to receive SNMP V3 trap using snmptrad sample code

### ISSUE THREAD

**Issue by User0805** [lextm/sharpsnmplib#83]
Hello,
SharpsnmpLib - v10.0.9
Win 10 platform
We are exploring SharpSnmpLib library and just wanted to test how SNMP V3 traps work with this library.We are only interested in using this for the manager not the agent.
Not interested in GET/SETs/WALKS or listener for the trap.
Trying to get the sample code for snmptrapd shipped with snmpsharplib 10.0.2 to RECEIVE Snmp V3 Trap sent from Dell server (configured SNMP traps using iDRAC 8).
Snmp v1 works fine and am able to receive traps. For v3 I'm trying to use AuthNoPriv setting and have configured the server to use SHA1 and no privacy.

I tested using PowerSNMP Free Manager and am able to get all v1/v2/v3 traps for the same server.

Are there any samples that show how to set up Auth/privacy provider properly especially for AuthNoPriv setting. Does receiving SNMP v3 trap require any other configuration on the library side?
Any help is really appreciated.
Here's the code I'm using from the snmptrapd sample. 
Only change made is to add a User with AuthNoPriv to match the configured user.

 var users = new UserRegistry();
            users.Add(new OctetString("neither"), DefaultPrivacyProvider.DefaultPair);
            users.Add(new OctetString("authen"), new DefaultPrivacyProvider(new MD5AuthenticationProvider(new OctetString("authentication"))));
            if (DESPrivacyProvider.IsSupported)
            {
                users.Add(new OctetString("privacy"), new DESPrivacyProvider(new OctetString("privacyphrase"),
                                                                            new MD5AuthenticationProvider(new OctetString("authentication"))));
            }

            if (AESPrivacyProviderBase.IsSupported)
            {
                users.Add(new OctetString("aes"), new AESPrivacyProvider(new OctetString("privacyphrase"), new MD5AuthenticationProvider(new OctetString("authentication"))));
                users.Add(new OctetString("aes192"), new AES192PrivacyProvider(new OctetString("privacyphrase"), new MD5AuthenticationProvider(new OctetString("authentication"))));
                users.Add(new OctetString("aes256"), new AES256PrivacyProvider(new OctetString("privacyphrase"), new MD5AuthenticationProvider(new OctetString("authentication"))));
            }
// Add provider for AuthNopriv 

            SHA1AuthenticationProvider authen = new SHA1AuthenticationProvider(new OctetString("AdminPwd"));
            users.Add(new OctetString("AdminUser"), new DefaultPrivacyProvider(authen));
           
            var trapv1 = new TrapV1MessageHandler();
            trapv1.MessageReceived += WatcherTrapV1Received;
            var trapv1Mapping = new HandlerMapping("v1", "TRAPV1", trapv1);

            var trapv2 = new TrapV2MessageHandler();
            trapv2.MessageReceived += WatcherTrapV2Received;
            var trapv2Mapping = new HandlerMapping("v2,v3", "TRAPV2", trapv2);

            var inform = new InformRequestMessageHandler();
            inform.MessageReceived += WatcherInformRequestReceived;
            var informMapping = new HandlerMapping("v2,v3", "INFORM", inform);

            var store = new ObjectStore();
            var v1 = new Version1MembershipProvider(new OctetString("public"), new OctetString("public"));
            var v2 = new Version2MembershipProvider(new OctetString("public"), new OctetString("public"));
            var v3 = new Version3MembershipProvider();
            var membership = new ComposedMembershipProvider(new IMembershipProvider[] { v1, v2, v3 });
            var handlerFactory = new MessageHandlerFactory(new[] { trapv1Mapping, trapv2Mapping, informMapping });

            var pipelineFactory = new SnmpApplicationFactory(store, membership, handlerFactory);
            using (var engine = new SnmpEngine(pipelineFactory, new Listener { Users = users }, new EngineGroup()))
            {
                engine.Listener.AddBinding(new IPEndPoint(IPAddress.Any, 162));
                engine.Start();
                Console.WriteLine("#SNMP is available at https://sharpsnmp.com");
                Console.WriteLine("Press any key to stop . . . ");
                Console.Read();
                engine.Stop();
            }
        }

        private static void WatcherInformRequestReceived(object sender, InformRequestMessageReceivedEventArgs e)
        {
            Console.WriteLine("INFORM version {0}: {1}", e.InformRequestMessage.Version, e.InformRequestMessage);
        }

        private static void WatcherTrapV2Received(object sender, TrapV2MessageReceivedEventArgs e)
        {
            Console.WriteLine("TRAP version {0}: {1}", e.TrapV2Message.Version, e.TrapV2Message);
        }

        private static void WatcherTrapV1Received(object sender, TrapV1MessageReceivedEventArgs e)
        {
            Console.WriteLine("TRAP version {0}; {1}", e.TrapV1Message.Version, e.TrapV1Message);
        }

**Comment by User0805** [comment]
@lextm  will appreciate your response.
Can you confirm is discovery is done automatically for snmp v3 traps? Your sample code does not seem to include discovery process. Can you please confirm if SnmpV3 traps works on windows 10 with lib version10.0.9.
I have configured Dell server to send Snmp V3 traps (AuthNopriv). Using the sample code above am unable to receive any traps when I send test traps from the server.

**Comment by lextm** [comment]
The samples were not up-to-date, compared to the integration test cases,

https://github.com/lextm/sharpsnmplib/blob/master/Tests/CSharpCore/Integration/TrapDaemonTestFixture.cs

So in your case, please refer to them instead. I will see if later I can fix the sample project.

**Comment by User0805** [comment]
Hi Lex,

I was able to get snmpv3 traps to work after setting the correct EngineId in the privacy provider.

I'm getting the engine Id using Discovery. I'm hitting a new issue though.

We want the ability to add multiple users to the user Registry for multiple agenst we want to catch traps from.

If they all have same user name ie Administrator , User Registry does not allow me to add auser List with same name.

How can I make it work? So we have  lets saw 4 BMCs we configure with same user name.

I'm able to get the engine Id by discovery for each but to add all these users at once to the user registry its taking only last one as it has same name


public async static Task TestTrapV2HandlerWithV3Message()

{





// get Engine Id using discovery

Dictionary<string, string> nodeEngineIdMapping = new Dictionary<string,string>();

nodeEngineIdMapping.Add("100.xx.xxx.xxx", "");

nodeEngineIdMapping.Add("100.xx.xxx.xxx", "");

var userList = new List<User>();

Discovery discovery = Messenger.GetNextDiscovery(SnmpType.GetRequestPdu);

ReportMessage report;

userList.Add(new User(new OctetString("neither"), DefaultPrivacyProvider.DefaultPair));

foreach (var nodeIp in nodeEngineIdMapping.Keys)

{

report = await discovery.GetResponseAsync(new IPEndPoint(IPAddress.Parse(nodeIp), 161));

string engineIdStr = BitConverter.ToString(report.Parameters.EngineId.ToBytes());

engineIdStr = engineIdStr.Replace("-", "").Trim().Substring(4);\


// convert back to OctetString

var engineId = new OctetString(ByteTool.Convert(engineIdStr));

var authenticationProvider = new SHA1AuthenticationProvider(new OctetString("pppp"));

if (DESPrivacyProvider.IsSupported)

{

var privacyProvider = new DESPrivacyProvider(new OctetString("ppp"), authenticationProvider)

{

EngineId = engineId

};

var newUser = new User(new OctetString("Administrator"), privacyProvider);

userList.Add(newUser);

}

}

var userArr = userList.ToArray();

var users = new UserRegistry(userArr);   <<<<<<< HERE DOES NOT TAKE MULTIPLE USERS WITH same name Administrator



var count = 0;

var trapv1 = new TrapV1MessageHandler();

var trapv1Mapping = new HandlerMapping("v1", "TRAPV1", trapv1);

var trapv2 = new TrapV2MessageHandler();

var trapv2Mapping = new HandlerMapping("v2,v3", "TRAPV2", trapv2);

trapv2.MessageReceived += WatcherTrapV2Received;



var inform = new InformRequestMessageHandler();

var informMapping = new HandlerMapping("v2,v3", "INFORM", inform);

var store = new ObjectStore();

var v1 = new Version1MembershipProvider(new OctetString("public"), new OctetString("public"));

var v2 = new Version2MembershipProvider(new OctetString("public"), new OctetString("public"));

var v3 = new Version3MembershipProvider();

var membership = new ComposedMembershipProvider(new IMembershipProvider[] { v1, v2, v3 });

var handlerFactory = new MessageHandlerFactory(new[] { trapv1Mapping, trapv2Mapping, informMapping });

var pipelineFactory = new SnmpApplicationFactory(store, membership, handlerFactory);

var engine = new SnmpEngine(pipelineFactory, new Listener { Users = users }, new EngineGroup());

var daemonEndPoint = new IPEndPoint(IPAddress.Any, 162);

//new IPEndPoint(IPAddress.Loopback, port.NextId);

engine.Listener.AddBinding(daemonEndPoint);

engine.Start();

Console.WriteLine("#SNMP is available at https://sharpsnmp.com");

Console.WriteLine("Press any key to stop . . . ");

Console.Read();

engine.Stop();


________________________________

**Comment by User0805** [comment]
@lextm Will appreciate your response on this.
Library

**Comment by User0805** [comment]
@lextm 
Hi Lex,
I was able to get snmpv3 traps to work after setting the correct EngineId in the privacy provider.
I'm getting the Engine Id using Discovery for each node I want to receive traps from.
Your library seems to work for SNMP v3 traps only if I set the correct engineid to the Privacyprovider for each agent I want to receive traps from. 
I'm hitting a new issue though.
We want the ability to add multiple users to the User Registry for multiple agents we want to catch traps from. In our setup all the physical nodes will have the same user name ,though their engineId will be unique.
But If they all have same user name ie Administrator , User Registry does not allow me to add users with same name.
I noticed in your UserRegistry.cs you remove users with same name and are using just name alone as the Key.
Question: Why don't you use some other value as key, isn't this a common scenario where multiple agents with unique engineId can have same user name lets say Administrator.

Please let us know if there is a workaround for this. If not I'd like to submit a PR to modify UserRegistry to add by engineID and also will have to modify Listener class.

We have invested few months of time in getting this to work so I'd really appreciate your response and help in get this going.
Thanks

**Comment by lextm** [comment]
The followup went to #94.
