### ISSUE TITLE
No results when using Messenger.Walk in a foreach loop

### ISSUE THREAD

**Issue by szilardx** [lextm/sharpsnmplib#96]
I am getting a strange behavior which I cannot  explain. It must be pretty straightforward, I am looking for an explanation.

If I use Messenger.Walk like this:

````     
       foreach (var item in devices)
       {
                List<Variable> res = new List<Variable>();
                Messenger.Walk(....., res, .......);
        } 
````

The count of "res" on one specific network for a set of devices is 0. I work on 200+ network with a huge number of devices, where this code works fine.

I I use the code this way - calling Messenger.Walk in a method, and returning the resulting List, the code works for the problematic network too:
````     
        foreach (var item in devices)
        {
                List<Variable> res = MethodCallingMessengerWalk(....);
        } 
````

I am sure this is something obvious, so please excuse my stupidity. I am just looking for an explanation.

I have posted a question here with a more verbose code:
https://stackoverflow.com/questions/53339917/unexpected-results-with-value-assignment-in-a-foreach-loop-sharpsnmplib

**Comment by lextm** [comment]
Cannot reproduce it.
