### ISSUE TITLE
TrapV2Message Engine Id Value

### ISSUE THREAD

**Issue by mjsiers** [lextm/sharpsnmplib#97]
Trying to get a client application to send a V3 trap message to an OpenNMS instance.
The sample code is using a hard coded string of "80001F8880E9630000D61FF449" for
the Engine Id value.  What does this engine id string represent?

**Comment by lextm** [comment]
It is a sample project, so the hard coded string is just some bytes. If you need to develop your own agent, please read the protocol documents for more details,

https://tools.ietf.org/html/rfc5343#page-4
